// pages/blog/index.vue
<template lang="html">
  <div>
    <div class="jumbotron jumbotron-fluid yep-geel">
      <div class="row justify-content-around">
        <h1>Blog</h1>
      </div>
    </div>
    <div class="container mt-4 larger">
      <div v-for="article of articles" :key="article.title">
        <b-card class="mt-2 overflow-hidden shadow-none p-4" no-body="">
          <b-row no-gutters="">
            <b-col lg="3" md="4">
              <div class="square-img-container">
                <b-card-img class="square-img rounded-circle" :src="require(`~/content/blog/${article.img}?size=500`)" :alt="article.alt"></b-card-img>
              </div>
            </b-col>
            <b-col lg="9" md="8">
              <b-card-body :title="article.title">
                <b-card-text>
                  <p>{{ article.tags }}</p>
                  <p>{{ article.categories }}</p>
                  <p>{{ article.intro }}</p>
                </b-card-text>
              </b-card-body>
            </b-col>
            <nuxt-link class="stretched-link font-bold" :to="{ name: `blog-slug`, params: { slug: article.slug } }"> </nuxt-link>
          </b-row>
        </b-card>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  async asyncData({ $content }) {
    const articles = await $content('blog').only(['title', 'slug', 'img', 'alt', 'intro']).sortBy('date', 'desc').limit(100).fetch()
    return {
      articles
    }
  },
  head() {
    return {
      title: 'Yep Trainingen'
    }
  },
  methods: {
    formatDate(date) {
      const options = { year: 'numeric', month: 'short', day: 'numeric' }
      return new Date(date).toLocaleDateString('en', options)
    }
  }
}
</script>

// src/routes/blog/+page.svelte
<script lang="ts">
	import type { BlogModule, ImageModule, Blog } from '$lib/types';

	const imageModules = import.meta.glob(
		'$content/blog/*.{avif,gif,heif,jpeg,jpg,png,tiff,webp,svg}',
		{
			eager: true,
			query: {
				enhanced: true
			}
		}
	) as Record<string, ImageModule>;

	const blogModules = import.meta.glob('$content/blog/*.md', {
		eager: true,
		query: {
			enhanced: true
		}
	}) as Record<string, BlogModule>;

	function formatDate(date: string) {
		const options: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'short', day: 'numeric' };
		return new Date(date).toLocaleDateString('en', options);
	}

	const blogs: Blog[] = Object.entries(blogModules)
		.map(([path, module]) => ({
			path: path.replace(/\.md$/, ''),
			name: path.replace(/\.md$/, '').split('/').pop(),
			meta: module.metadata,
			content: module.default
		}))
		.sort((a, b) => new Date(b.meta.date).getTime() - new Date(a.meta.date).getTime());
</script>

<template lang="pug">
    div
      .jumbotron.jumbotron-fluid.yep-geel
        .row.justify-content-around
          h1 Blog
      .container.mt-4.larger
        +each('blogs as blog')
          .card.mt-2.overflow-hidden.shadow-none.p-4(style="border: 1px solid #ddd; border-radius: 0.25rem;")
            .row.no-gutters
              .col-lg-3.col-md-4
                .square-img-container
                  enhanced:img.square-img.rounded-circle(src="{imageModules[`/content/blog/${blog.meta.img}`].default}" alt="{blog.meta.alt}")
              .col-lg-9.col-md-8(style="display: flex; flex-direction: column; justify-content: center;")
                .card-body(style="display: flex; flex-direction: column; justify-content: center;")
                  h2.card-title {blog.meta.title}
                  .card-text
                    small.text-muted {formatDate(blog.meta.date)}
                    p {blog.meta.intro}
              a.stretched-link.font-bold(href=`/blog/{blog.name}`)
</template>
