// src/routes/contact/+page.svelte
<script lang="ts">
	import * as m from '$lib/paraglide/messages.js';
</script>

<template lang="html">
	<div>
		<div class="jumbotron jumbotron-fluid yep-geel">
			<div class="container">
				<div class="row justify-content-around">
					<h1>{m.contact_title()}</h1>
				</div>
			</div>
		</div>
		<div class="container p-4 text-center">
			<h2>{m.contact_company_name()}</h2>
			<p innerHTML={m.contact_address()}></p>
			<p>{m.contact_information()}</p>
			<p>{m.contact_training()}</p>
			<p innerHTML={m.contact_kvk()}></p>
			<p innerHTML={m.contact_vat()}></p>
			<p innerHTML={m.contact_iban()}></p>
		</div>

		<div class="container_fluid mt-6 p-4 bg-white">
			<div class="container">
				<form
					id="mc4wp-form-1"
					class="mc4wp-form mc4wp-form-1369 mc4wp-form-theme mc4wp-form-theme-green"
					method="post"
					data-id="1369"
					data-name="Volg onze nieuwsbrief"
				>
					<div class="mc4wp-form-fields">
						<h2>{m.contact_newsletter_title()}</h2>
						<p>
							{m.contact_newsletter_text()}
						</p>

						<p>
							<label for="contact-name">{m.contact_name_label()}</label><br />
							<input
								id="contact-name"
								type="text"
								name="NAAM"
								placeholder={m.contact_name_placeholder()}
								required=""
							/>
						</p>
						<p>
							<label for="contact-email">{m.contact_email_label()}:</label><br />
							<input
								id="contact-email"
								type="email"
								name="EMAIL"
								placeholder={m.contact_email_placeholder()}
								required
							/>
						</p>
						<p>
							<input type="submit" value={m.contact_submit()} />
						</p>
						{m.contact_privacy()}
					</div>
					<label style="display: none !important"
						>{m.contact_honeypot()}
						<input type="text" name="_mc4wp_honeypot" value="" tabindex="-1" autocomplete="off" />
					</label>
					<input type="hidden" name="_mc4wp_timestamp" value="1639488557" />
					<input type="hidden" name="_mc4wp_form_id" value="1369" />
					<input type="hidden" name="_mc4wp_form_element_id" value="mc4wp-form-1" />
					<div class="mc4wp-response"></div>
				</form>
			</div>
		</div>
	</div>
</template>

// pages/contact.vue
<template lang="html">
  <div>
    <div class="jumbotron jumbotron-fluid yep-geel">
      <div class="container">
        <div class="row justify-content-around">
          <h1>Contact</h1>
        </div>
      </div>
    </div>
    <div class="container p-4 text-center">
      <h2>Yep Trainingen</h2>
      <p>
        <br />
        
      </p>
      <p>Neem voor informatie contact op:</p>
      <p>Voor trainingsaanbod met Marijn: info@yeptrainingen.nl // 085-7606266</p>
      <p>Voor coachingsaanbod met Anna: anna@yeptrainingen.nl // 0653628112</p>
      <p><strong>KvK:</strong> 58989463</p>
      <p><strong>BTW:</strong> NL154101643B02</p>
      <p><strong>IBAN:</strong> NL49TRIO0254729886</p>
    </div>

    <div class="container_fluid mt-6 p-4 bg-white">
      <div class="container">
        <form
          id="mc4wp-form-1"
          class="mc4wp-form mc4wp-form-1369 mc4wp-form-theme mc4wp-form-theme-green"
          method="post"
          data-id="1369"
          data-name="Volg onze nieuwsbrief"
        >
          <div class="mc4wp-form-fields">
            <H2> Nieuwsbrief</H2>
            <p>Blijf op de hoogte en meld je aan voor onze Nieuwsbrief (ongeveer 1x per kwartaal)</p>

            <p>
              <label>Naam</label><br />
              <input type="text" name="NAAM" placeholder="voor- en achternaam" required="" />
            </p>
            <p>
              <label>Emailadres: </label><br />
              <input type="email" name="EMAIL" placeholder="je mailadres" required />
            </p>
            <p>
              <input type="submit" value="Aanmelden" />
            </p>
            Wij beloven zorgvuldig om te gaan met je gegevens en deze nooit aan derden te verstrekken!
          </div>
          <label style="display: none !important"
            >Laat dit veld leeg als je een mens bent:
            <input type="text" name="_mc4wp_honeypot" value="" tabindex="-1" autocomplete="off" />
          </label>
          <input type="hidden" name="_mc4wp_timestamp" value="1639488557" />
          <input type="hidden" name="_mc4wp_form_id" value="1369" />
          <input type="hidden" name="_mc4wp_form_element_id" value="mc4wp-form-1" />
          <div class="mc4wp-response"></div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from 'vue'

export default Vue.extend({})
</script>
