// src/routes/tarieven/+page.svelte
<template lang="html">
	<div>
		<div class="jumbotron jumbotron-fluid yep-geel">
			<div class="row justify-content-around">
				<h1>Tarieven</h1>
			</div>
		</div>
		<div class="container bg-white mt-4">
			<div class="row">
				<div class="col-md-6 p-4">
					<h2>Yep rekent:</h2>
					<p>
						Een dagdeeltarief voor het geven van trainingen, voor voorbereidende werkzaamheden en
						een coaching tarief.
					</p>
					<p>
						De trainingstarieven gelden per groep (3-12 personen) en zijn exclusief btw. Wij rekenen
						een gereduceerd coachingstarief van 105 euro per uur voor particulieren (btw-vrij) en
						ZZP'ers (excl. btw)
					</p>
					<p>
						Wij zijn geregistreerd bij het CRKBO en hebben daardoor de mogelijkheid om btw-vrij te
						factureren. Komt dit uw organisatie beter uit, laat het ons weten, dan houden we hier op
						de offerte rekening mee. Wel verhogen wij dan de tarieven om 10% om de extra kosten te
						kunnen dekken die deze registratie (direct en indirect) met zich meebrengt. Het netto
						voordeel voor uw organisatie is zodoende 11%.
					</p>
				</div>
				<div class="col-md-6 p-4" style="background-color: lightgrey">
					<table class="table mt-5">
						<tbody>
							<tr>
								<td>Trainingen</td>
								<td>€550 per dagdeel</td>
							</tr>
							<tr>
								<td>Voorbereidende werkzaamheden</td>
								<td>€400 per dagdeel</td>
							</tr>
							<tr>
								<td>Coaching</td>
								<td>€150 per uur, minimum van 2 uur.</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="container-fluid bg-white mt-4 text-center">
			<enhanced:img class="fluid" src="/static/CRKBO_erkenning.jpg" />
		</div>
	</div>
</template>

// pages/tarieven.vue
<template lang="html">
  <div>
    <div class="jumbotron jumbotron-fluid yep-geel">
      <div class="row justify-content-around">
        <h1>Tarieven</h1>
      </div>
    </div>
    <div class="container bg-white mt-4">
      <div class="row">
        <div class="col-md-6 p-4">
          <h2>Yep rekent:</h2>
          <p>Een dagdeeltarief voor het geven van trainingen, voor voorbereidende werkzaamheden en een coaching tarief.</p>
          <p>
            De trainingstarieven gelden per groep (3-12 personen) en zijn exclusief btw. Wij rekenen een gereduceerd coachingstarief van 105 euro per uur voor
            particulieren (btw-vrij) en ZZP’ers (excl. btw)
          </p>
          <p>
            Wij zijn geregistreerd bij het CRKBO en hebben daardoor de mogelijkheid om btw-vrij te factureren. Komt dit uw organisatie beter uit, laat het ons
            weten, dan houden we hier op de offerte rekening mee. Wel verhogen wij dan de tarieven om 10% om de extra kosten te kunnen dekken die deze
            registratie (direct en indirect) met zich meebrengt. Het netto voordeel voor uw organisatie is zodoende 11%.
          </p>
        </div>
        <div class="col-md-6 p-4" style="background-color: lightgrey">
          <table class="table mt-5">
            <tbody>
              <tr>
                <td>Trainingen</td>
                <td>€550 per dagdeel</td>
              </tr>
              <tr>
                <td>Voorbereidende werkzaamheden</td>
                <td>€400 per dagdeel</td>
              </tr>
              <tr>
                <td>Coaching</td>
                <td>€150 per uur, minimum van 2 uur.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="container-fluid bg-white mt-4 text-center">
      <b-img fluid="fluid" blank-color="#777" src="~/static/CRKBO_erkenning.jpg" :srcset="require(`~/static/CRKBO_erkenning.jpg`).srcSet"></b-img>
    </div>
  </div>
</template>

<script>
import Vue from 'vue'

export default Vue.extend({})
</script>
