// pages/werkgevers.vue
<template lang="html">
    <div class="container-fluid m-0 p-0 bg-white">
      <div class="row">
        <div class="col-md-6 p-0">
            <b-img
            fluid="fluid"
            blank-color="#777"
            src="~/assets/images/site-foto-1-of-1-3.jpg"
            :srcset="require(`~/assets/images/site-foto-1-of-1-3.jpg`).srcSet"
            ></b-img>
        </div>
        <div class="col-md-6 p-4">
          <h2>Maatschappelijke impact willen maken</h2>
          <p>Wij merken dat mensen dit willen doen vanuit mooie persoonlijke en maatschappelijke doelen: effectiviteit, persoonlijke energie, circulaire economie, vrije journalistiek, verduurzaming, kwetsbaren in de samenleving ondersteunen, de overheid transparant maken, kansen gelijkheid en de verbinding binnen het eigen team.</p>
          <p>Men start ambitieus en met veel inzet, maar komt hindernissen tegen die soms zo ontmoedigen dat de ambities naar de achtergrond verdwijnen. Er gaat weer licht schijnen op het moment dat professionals erachter komen dat hindernissen inherent zijn aan het werken in organisaties en dat speels omgaan met die obstakels een kunst is die zij zelf onder de knie kunnen krijgen.</p>
        </div>
      </div>
       <div class="container m-auto bg-white pt-4">
          <h2>Op zoek naar inzicht, durf en vaardigheid.</h2>
          <p>Het is onze missie om samen met professionals te werken aan al die inzichten, de durf en de vaardigheden die nodig zijn om hun gewenste impact ook echt te kunnen maken. We hebben een aanpak ontwikkeld die past bij gedreven professionals. Op deze pagina lees je meer over de kenmerken van onze doelgroep en de werkwijze die we hanteren.</p>
          <p>&nbsp;</p>
          <h2>Kenmerken van onze doelgroep.</h2>
          <p>In 2010 begeleidden we onze eerste deelnemer. Onze focus lag in het begin op jonge talenten. Inmiddels zijn we honderden groepen verder en we hebben gaandeweg gemerkt dat onze werkwijze ook heel aansprekend is voor meer ervaren professionals. Logisch ook: want iedereen, jong en oud, heeft immers eens in de zoveel tijd behoefte aan een nieuwe impuls. We werken daarom niet alleen meer voor young professionals, maar ook voor ervaren krachten die hun stem (verder) willen ontdekken en laten horen. Vaak gaat het om professionals die maatschappelijke impact willen maken. Medewerkers die hun vleugels uit willen slaan en staan te popelen om zich te ontwikkelen. Heerlijk om op die manier de maatschappelijke organisaties die wij belangrijk vinden te kunnen ondersteunen in de drive om te vernieuwen, aan te blijven sluiten op wat er nodig is in de maatschappij en op de werkvloer.</p>
          <p>Wat hebben mensen die maatschappelijk (meer) impact willen maken met elkaar gemeen? De gedreven professionals die we binnen meer dan 20 gemeenten en vele stichtingen, verenigingen en commerciële bedrijven begeleidden, delen een aantal kenmerken. We noemen de belangrijkste kenmerken en laten aan de hand van een aantal voorbeelden zien hoe we die vertalen in onze werkwijze.</p>
       </div>
        <div class="jumbotron jumbotron-fluid mt-5" style="background-color: #585656">
        </div>
        <div class="jumbotron jumbotron-fluid" style="background-color: #F2F2F2;">
          <div class="row">
            <div class="col-md-8 p-4">
              <h2 class="text-center">Tips</h2>
              <p>Herken je de kenmerken bij je eigen medewerkers? Hoe beter je je medewerkers kent en hoe beter je ze hun positieve eigenschappen kunt aanboren, hoe meer ze de organisatie te bieden hebben. Alvast een paar tips:</p>
              <ul>
              <li>Stel je medewerkers regelmatig de vraag welke maatschappelijke impact zij zouden willen leveren. Wees oprecht nieuwsgierig naar de ideeën die je mensen hebben.</li>
              <li>Zorg voor een inspirerende stip op de horizon en onderzoek of je medewerkers zich daarmee verbonden voelen. Geef je medewerkers vervolgens zoveel mogelijk autonomie om zelf invulling te geven aan het &#8216;hoe?&#8217;</li>
              <li>Introduceer een cultuur van spelen en experimenteren, waarbij het toegestaan is om iets te proberen, zonder eraan vast te zitten. Dit geeft lucht voor die medewerkers bij wie perfectionisme in de weg zit.</li>
              </ul>
            </div>
            <div class="col-md-4">
              
            </div>
          </div>
        </div>

    </div>
   
</template>

<script>
import Vue from 'vue'

export default Vue.extend({})
</script>

// src/routes/werkgevers/+page.svelte
<template lang="html">
	<div class="container-fluid m-0 p-0 bg-white">
		<div class="row">
			<div class="col-md-6 p-0">
				<enhanced:img
					style="width:100%; height:auto;"
					src="/static/images/site-foto-1-of-1-3.jpg"
					alt="yeptrainingen"
				/>
			</div>
			<div class="col-md-6 p-4">
				<h2>Maatschappelijke impact willen maken</h2>
				<p>
					Wij merken dat mensen dit willen doen vanuit mooie persoonlijke en maatschappelijke
					doelen: effectiviteit, persoonlijke energie, circulaire economie, vrije journalistiek,
					verduurzaming, kwetsbaren in de samenleving ondersteunen, de overheid transparant maken,
					kansen gelijkheid en de verbinding binnen het eigen team.
				</p>
				<p>
					Men start ambitieus en met veel inzet, maar komt hindernissen tegen die soms zo
					ontmoedigen dat de ambities naar de achtergrond verdwijnen. Er gaat weer licht schijnen op
					het moment dat professionals erachter komen dat hindernissen inherent zijn aan het werken
					in organisaties en dat speels omgaan met die obstakels een kunst is die zij zelf onder de
					knie kunnen krijgen.
				</p>
			</div>
		</div>
		<div class="container m-auto bg-white pt-4">
			<h2>Op zoek naar inzicht, durf en vaardigheid.</h2>
			<p>
				Het is onze missie om samen met professionals te werken aan al die inzichten, de durf en de
				vaardigheden die nodig zijn om hun gewenste impact ook echt te kunnen maken. We hebben een
				aanpak ontwikkeld die past bij gedreven professionals. Op deze pagina lees je meer over de
				kenmerken van onze doelgroep en de werkwijze die we hanteren.
			</p>
			<p>&nbsp;</p>
			<h2>Kenmerken van onze doelgroep.</h2>
			<p>
				In 2010 begeleidden we onze eerste deelnemer. Onze focus lag in het begin op jonge talenten.
				Inmiddels zijn we honderden groepen verder en we hebben gaandeweg gemerkt dat onze werkwijze
				ook heel aansprekend is voor meer ervaren professionals. Logisch ook: want iedereen, jong en
				oud, heeft immers eens in de zoveel tijd behoefte aan een nieuwe impuls. We werken daarom
				niet alleen meer voor young professionals, maar ook voor ervaren krachten die hun stem
				(verder) willen ontdekken en laten horen. Vaak gaat het om professionals die
				maatschappelijke impact willen maken. Medewerkers die hun vleugels uit willen slaan en staan
				te popelen om zich te ontwikkelen. Heerlijk om op die manier de maatschappelijke
				organisaties die wij belangrijk vinden te kunnen ondersteunen in de drive om te vernieuwen,
				aan te blijven sluiten op wat er nodig is in de maatschappij en op de werkvloer.
			</p>
			<p>
				Wat hebben mensen die maatschappelijk (meer) impact willen maken met elkaar gemeen? De
				gedreven professionals die we binnen meer dan 20 gemeenten en vele stichtingen, verenigingen
				en commerciÃ«le bedrijven begeleidden, delen een aantal kenmerken. We noemen de
				belangrijkste kenmerken en laten aan de hand van een aantal voorbeelden zien hoe we die
				vertalen in onze werkwijze.
			</p>
		</div>
		<div class="jumbotron jumbotron-fluid mt-5" style="background-color: #585656"></div>
		<div class="jumbotron jumbotron-fluid" style="background-color: #f2f2f2">
			<div class="row">
				<div class="col-md-8 p-4">
					<h2 class="text-center">Tips</h2>
					<p>
						Herken je de kenmerken bij je eigen medewerkers? Hoe beter je je medewerkers kent en hoe
						beter je ze hun positieve eigenschappen kunt aanboren, hoe meer ze de organisatie te
						bieden hebben. Alvast een paar tips:
					</p>
					<ul>
						<li>
							Stel je medewerkers regelmatig de vraag welke maatschappelijke impact zij zouden
							willen leveren. Wees oprecht nieuwsgierig naar de ideeÃ«n die je mensen hebben.
						</li>
						<li>
							Zorg voor een inspirerende stip op de horizon en onderzoek of je medewerkers zich
							daarmee verbonden voelen. Geef je medewerkers vervolgens zoveel mogelijk autonomie om
							zelf invulling te geven aan het &#8216;hoe?&#8217;
						</li>
						<li>
							Introduceer een cultuur van spelen en experimenteren, waarbij het toegestaan is om
							iets te proberen, zonder eraan vast te zitten. Dit geeft lucht voor die medewerkers
							bij wie perfectionisme in de weg zit.
						</li>
					</ul>
				</div>
				<div class="col-md-4"></div>
			</div>
		</div>
	</div>
</template>
